### ISSUE TITLE
Why does it create different databases for each symbol?

### ISSUE THREAD

**Issue by imperative** [JamesKBowler/fxcmminer#3]
It is far more logical to create a new set of tables (properly named) for each of the timeframes for each symbol, and keep them all in the same database. 

Is there any practical reason why the choice was made to put them into different databases? Is there some caveat to think about?

**Comment by zerrrow** [comment]
Very logical. It should be like this based on relational database logic. Can we choose which symbols to download, not all of them and  probably some old entries should be deleted in real time trading, because you can hold all historty for all instruments.

**Comment by zerrrow** [comment]
Does it work on any linux server or it is ubuntu specific?
